# Generated by Django 3.0.3 on 2020-02-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0002_auto_20200221_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='auto',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='autor'),
        ),
    ]
